### ISSUE TITLE
feedback 3

### ISSUE THREAD

**Issue by PatNei** [ITU-BDSA23-GROUP8/Chirp#113]
# Group 8 
✔ <- Jeres side er ikke oppe og køre på azure 

bruger i en dockerized mssql server til development? ✔

jeres projekt builder med 23 warnings. bør hvor 0 når i aflevere jeres projekt :) 

Tip til jeres test, i kan lave en constructor til jeres tests, så kan i rykke redundant kode ud i den.
f.eks. jeres deklaration af contexten og sqlite 

Ingen integration test eller e2e bør nok være nogle inden i afleverer. ✔

Af nysgerrighed er der en grund til gør det her i jeres program.cs
```csharp

var dbPath = Path.GetTempPath() + "chirp.db";
builder.Configuration["ConnectionStrings:ChirpSQlite"] = $"Data Source={dbPath}";
Console.WriteLine(dbPath);

var conStr = builder.Configuration.GetConnectionString("ChirpSQlite");

```

Ligner ikke at der er en restriction på hvor mange chars et tweet må være right? det skal være max 160 chars både front og back end

Følgende kode bruger data annotations (det er noget syntax i csharp efcore) [dotnet documentation](https://learn.microsoft.com/en-us/ef/ef6/modeling/code-first/data-annotations)
```csharp
public class cheep(){
[MaxLength(160, ErrorMessage = "hello")] // Defined minimum length is not required
public string text;
}
```

Kan man logge ind via github på jeres side?

Kan man følge hinanden eller er det undervejs? :)

Godt arbejde!

**Comment by SDeLaVida** [comment]
I kan altid lige skrive, hvis der var noget vi ikke fik talt om :)

**Comment by SDeLaVida** [comment]
Det ligner btw. at jeg kan register men ikke at jeg kan logge ind på jeres hjemme side

**Comment by SDeLaVida** [comment]
- Skal man stadig have register på sin side. (gruppe 8) <- Kun login knappen er vigtig og man skal kunne logge ind med github også selvom det er første gang.

Der skal ikke være noget email verifikation når man logger ind.
	- Azure b2c der kan man få en knap hvor man kan skippe hele email og kode verifikations delen

**Comment by SDeLaVida** [comment]
´- Du nævnte at prøven omhandler det der er at finde på slides men hvad gør man med rasmus slides, vil det være at finde til prøven (gruppe 8)
	- I må bruge bogen i de uger hvor rasmus har lavet forlæsninger.
