### ISSUE TITLE
5) 1.c - Add initial testing

### ISSUE THREAD

**Issue by SarahVestergren** [ITU-BDSA23-GROUP8/Chirp#37]
**User story:**

As a developer, I want to refactor the test suite from our previous Chirp! CLI application. That is, keep all those test cases around that still apply to the new Razor Page application. Likely, these are some unit tests and perhaps a few suitable integration tests. Due to their dependency on CLI parameters and output, the previous end-to-end tests likely do not apply anymore, so that our test is up to date. 

Add some new API tests. These should send GET requests to the endpoints for public and private timelines (/ and /<username> respectively) and assert that certain information is in the HTML text of the response in the HTTP body. 

**Acceptance criteria:**
- Our current test is up to date. 
- Add new API tests, that send GET requests to the endpoint for public and private timelenes and assert certain information in the HTML text of the response in the HTTP body. 

**Other:**
Add some new API tests. For example: 
- https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_05/data/dump.sql)
a response body for a GET request send to / shall contain a cheep written by Helge and the content of a cheep shall be Hello, BDSA students! Similarly, a response body for a GET request send to /Rasmus shall contain a cheep written by Rasmus with the content Hej, velkommen til kurset.

**Comment by AnnikaJensby** [comment]
---> pseudo code added + folder added , so essentially tests are ready to go. 
due to internal server error 500, TA's said they need to figure out a fix for this, since all were having this issue. 
So we will move to close and then further complete the tests when entering week 6's assignements.
