### ISSUE TITLE
7) 1.a - Use in-memory SQLite database for testing

### ISSUE THREAD

**Issue by ClaraSoenderborg** [ITU-BDSA23-GROUP8/Chirp#52]
As a developer, I want to use an in-memory database for testing, so we don't have direct dependency for a certain database. 

Configure integration test to use in-memory database

**Acceptance criteria:**

- Integration tests now use in-memory database
- Tests no longer depend on a live database

**Comment by SarahVestergren** [comment]
We use in-memory for all unit-test, but because we dont have any integration test (for now), we dont meet this acceptance criteria yet.
